//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitaciones
    {
        public int IdHabitacion { get; set; }
        public Nullable<int> Hotel { get; set; }
        public string TipoHabitacion { get; set; }
        public Nullable<int> NumHabitacion { get; set; }
        public string Comentario { get; set; }
    
        public virtual Hoteles Hoteles { get; set; }
    }
}
