//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifas
    {
        public int IdTarifa { get; set; }
        public Nullable<int> Hotel { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<double> Precio { get; set; }
    
        public virtual Hoteles Hoteles { get; set; }
    }
}
